# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Benjamin M. Kent
email: benjamin.kent@manchester.ac.uk
description: >- # this means to ignore newlines until "baseurl:"  Write an awesome description for your new site here. You can edit thisline in _config.yml. It will appear in your document head meta (forGoogle search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://benmkent.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  benmkent

# Build settings
theme: jekyll-swiss
#theme: minima-reboot
#theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jekyll-scholar
  
# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: 
social_username: 

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: bk

# Build settings
markdown: kramdown

excerpt_separator: "<!--more-->"
