deploy:
  needs: build
  runs-on: ubuntu-latest
  environment:
    name: github-pages
  permissions:
    contents: read
    pages: write
    id-token: write

  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Download artifact from build
      uses: actions/download-artifact@v4
      with:
        name: site
        path: ./_site   # everything for deployment goes here

    - name: Copy static assets
      run: |
        cp styles.css ./_site/
        if [ -d images ]; then cp -r images ./_site/; fi

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./_site

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
